### ISSUE TITLE
Se añade un menu rapido

### ISSUE THREAD

**Issue by elmer03** [NextSoftTis/seguimiento#21]
#### DESCRIPCION
Cuando ingreso al sistema no hay un buen manejo de las diferentes vistas.

#### ISOLACION

"Espacio Secretaria"

#### REQUERIMIENTOS
* una cuenta registrada
* seguimiento/index.php
* seguimiento/login.php
* seguimiento/espacioSecretaria.php
*seguimiento/views/*

#### PASOS

1.  Ingresar a la pagina  index.php.
2.  Ingresar a login.php e ingresar satisfactoriamente.
3.  Ingresar a las diferentes vistas del sistema.

#### RESULTADO ACTUAL
Error en la relacion de las vistas y botones ambiguos en el sistema.

#### RESULTADO ESPERADO
Deberiamos tener un menu rapido, para el facil manejo de las vistas existentes en el sistema web.

**Comment by jjohxx** [comment]
Esti esta como marcado ya realizado no? entonces done.
